### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by tylerthetiletiler** [vatpac-technology/sops#11]
Footer on Aerodrome pages is floating instead of fixed

I think we should remove the top footer directing people to cycle between the coordination and general sections.

**Comment by chrisg06** [comment]
Can you attach a screenshot of what you mean?

**Comment by tylerthetiletiler** [comment]
![Screen Shot 2022-10-30 at 2 53 52 am](https://user-images.githubusercontent.com/106805646/198866334-4ad99d4a-7125-464a-8c9e-276f41afa390.png)

Previous / Next to go between various tabs. Seems useless
