### ISSUE TITLE
Screen Break Burger Menu

### ISSUE THREAD

**Issue by samie11** [vatpac-technology/sops#146]
Burger menu on Nav but does not open when screen is certain size

**Comment by wsmart17** [comment]
I know this is a bit of a stale issue, but I just did a quick investigation and it seems related to [this line](https://github.com/vatpac-technology/sops/blob/7aab1a09565976707c7b2f071ce43d174de77783/overrides/assets/stylesheets/home.css#L164C10-L164C10) in `home.css`. When I changed the breakpoint on that statement to `1220px`, it seemed to be fine. I'm not sure of the larger implications of this change though so will leave for those who've worked with the system.

**Comment by chrisg06** [comment]
@samie11 and I did some investigating with it, was still having issues even after changing the breakpoint. Will have a look further when I am back.

**Comment by JoshuaMicallefYBSU** [comment]
@chrisg06 dont forget about this <3
