### ISSUE TITLE
MUN > TBD STAR Clearances

### ISSUE THREAD

**Issue by JoshuaMicallefYBSU** [vatpac-technology/sops#212]
During NN Event on the 20JAN24 it was identified aircraft reach TD before the MUN/TBD boundary. 

Might be worth making MUN responsible for STAR/DESC before handing off to TBD

**Comment by alphadelta332** [comment]
TBD is responsible for YPAD STAR Clearances IRL, that seems a bit strange that an aircraft would be TOD that early.

If an aircraft happens to report at TOD in MUN's airspace, MUN can handoff to TBD and they can give STAR clearance and descent. They would already have to be super close to the boundary at that point
