### ISSUE TITLE
Use lightbox for images

### ISSUE THREAD

**Issue by glennawatson** [vatpac-technology/sops#291]
Happy to do the work if people agree.

Be good to replace the existing images to use a lightbox, a lightbox is where you click the image and it expands it to full size.

Some of the ESL images for example could benefit from this.

**Comment by mattkelly4** [comment]
@glennawatson go for it, keen to see a prototype if you're able to share!

**Comment by glennawatson** [comment]
Fix added to https://github.com/vatpac-technology/sops/pull/296
