### ISSUE TITLE
BN SID Selection

### ISSUE THREAD

**Issue by bhendrie** [vatpac-technology/sops#355]
WACKO SID is not avail via RWY 01L. No SID exists for WACKO from 01L

**Comment by bhendrie** [comment]
Noting example "Non-Jet Aircraft planned via WACKO, assigned runway 01L, shall be assigned the BN (RADAR) SID." is a bad example cause no aircraft can take a procedural sid to WACKO from 01L

**Comment by alphadelta332** [comment]
> Noting example "Non-Jet Aircraft planned via WACKO, assigned runway 01L, shall be assigned the BN (RADAR) SID." is a bad example cause no aircraft can take a procedural sid to WACKO from 01L

Yep makes sense. Will refine this
