### ISSUE TITLE
Update Launceston Aerodrome Page to remove decommissioned runways

### ISSUE THREAD

**Issue by m-9c** [vatpac-technology/sops#357]
Hello. 

Launceston runways 14L/32R and 18/36 have been decommissioned. 

I've reproduced the image in the article using the updated vatSys data, if it helps. :)

![image](https://github.com/user-attachments/assets/9b380acc-51de-4d59-94a6-89444f5adbae)

**Comment by mattkelly4** [comment]
Will need to replace airspace diagram and circuit direction table
