### ISSUE TITLE
Controller Extensions

### ISSUE THREAD

**Issue by Verbjimtim** [vatpac-technology/sops#381]
![image](https://github.com/user-attachments/assets/882f529d-f1de-4b0d-ae91-c530e59fd3d9)
Vatsim radar is about to be checking controller info for extensions having an example in SOPs and maybe even a NOTAM when he pushes it to live next EOW
![image](https://github.com/user-attachments/assets/558b9656-447c-4544-a859-0ebce5a0da3d)

**Comment by alphadelta332** [comment]
https://discord.com/channels/343999482737721354/1308395757518327932/1308605770337878028

**Comment by mattkelly4** [comment]
@Verbjimtim current SOPs dictate this:
![image](https://github.com/user-attachments/assets/255c18eb-7566-4a00-9ec1-e79359832dc0)

Is that suitable or is more action required?

**Comment by Verbjimtim** [comment]
Ahh yes, @mattkelly4 , thank you no action is required. I shall close this. ~~i didnt forget about this issue i had open~~
