### ISSUE TITLE
YMLT 2412 Update

### ISSUE THREAD

**Issue by m-9c** [vatpac-technology/sops#386]
Hello.

As part of the most recent airac update, ONAGI was renamed FLIKI (along with the associated SID).

The SOPs for Launceston don't appear to have beent updated by https://github.com/vatpac-technology/sops/pull/380.

**Comment by alphadelta332** [comment]
Thanks for bringing this to our attention. the ONAGI waypoint is still there (FLIKI is exisiting too), just the YMLT SID has been changed from terminating at ONAGI to at FLIKI. This will be fixed in due course
