### ISSUE TITLE
AV TWR owning airspace consensus

### ISSUE THREAD

**Issue by alexd-332** [vatpac-technology/sops#55]
docs say by default, ML TCU owns the AV Class D, but seemingly it's often released to the Tower. So would we like it to be owned by TCU or TWR?

**Comment by mattkelly4** [comment]
If in practice it's operated by TWR and it's essentially never operated by APP, I'd say we give it to TWR

**Comment by zachbf** [comment]
I'm on board with that as a default yes. Class D tower with a surveillance approach service, just like Hobart, Launy, etc.
