### ISSUE TITLE
Side menu current page colour more defined

### ISSUE THREAD

**Issue by mattkelly4** [vatpac-technology/sops#62]
![image](https://user-images.githubusercontent.com/41880668/204113506-a3092a2d-6cc2-425b-802b-90e435ac4943.png)
(Brisbane is selected)

**Comment by chrisg06** [comment]
@mattkelly4 were you working on this one or want me to fix?

**Comment by mattkelly4** [comment]
@chrisg06 nah I haven't started looking into it, feel free to have a crack
