### ISSUE TITLE
Controller Skills files rename required

### ISSUE THREAD

**Issue by mattkelly4** [vatpac-technology/sops#66]
Some filenames are capitalised, others are not, so the alphabetic sort doesn't work:
![image](https://user-images.githubusercontent.com/41880668/205204361-6a3505fc-ef96-4f92-8ddf-af3ced7eb124.png)

Change all capitalised filenames to lower case.

Will need to go through all other files to find any references and update the links.

**Comment by chrisg06** [comment]
@mattkelly4 I'll sort this one
