### ISSUE TITLE
Standard Taxi Directions for Brisbane

### ISSUE THREAD

**Issue by chrisg06** [vatpac-technology/sops#73]
Brisbane aerodrome doesn't contain the standard taxi directions that were in the local instructions.

<img width="622" alt="image" src="https://user-images.githubusercontent.com/64582286/206631226-786e162a-7f46-4d3d-a506-55fd6bde3b40.png">

**Comment by oliverfrye** [comment]
Do you know if there is a name for the HLS (i.e. "Hotel 1" like in the YSSY SOPS)?
