### ISSUE TITLE
OLW + TRT

### ISSUE THREAD

**Issue by alexd-332** [vatpac-technology/sops#80]
These pages never got finished. I believe they were assigned to Zack?

**Comment by tylerthetiletiler** [comment]
Hope all is going well zkgell

**Comment by chrisg06** [comment]
Hi zkgell can we get an update please? well over a month. Poor standards and poor excuses.

**Comment by alexd-332** [comment]
Fark it I'll do it

**Comment by zkgell** [comment]
I for one do not like the SOPs page. It is confusing. I prefer the old ones.
