### ISSUE TITLE
BERNI bubble

### ISSUE THREAD

**Issue by alphadelta332** [vatpac-technology/sops#91]
BAC vs INL(GOL)

**Comment by alexd-332** [comment]
awaiting confirmation of removal of BERNI bubble in 2302

**Comment by mattkelly4** [comment]
Confirmed bubble to be removed by AIS staff.

**Comment by JoshuaMicallefYBSU** [comment]
As far as I can see this bubble still exists.
![image](https://github.com/vatpac-technology/sops/assets/91457812/3dcdf833-ba0e-493f-9e96-737b1d0194ba)

**Comment by mattkelly4** [comment]
> As far as I can see this bubble still exists. ![image](https://private-user-images.githubusercontent.com/91457812/290457273-3dcdf833-ba0e-493f-9e96-737b1d0194ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MDc3MzcsIm5iZiI6MTcwMjYwNzQzNywicGF0aCI6Ii85MTQ1NzgxMi8yOTA0NTcyNzMtM2RjZGY4MzMtYmEwZS00OTNmLTllOTYtNzM3YjFkMDE5NGJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDAyMzAzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhODdiZDBjOTIwODQxMzMwNWE2NzQzNjgxZGZhYzNhN2JlZDk5MmMwMjhkYjM5N2FmY2EwNjEzOWZlNzVhYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OSC2ui_wLoYCYxCp4h2XQ3Vxj8-43iJBNNk4fPfUaA4)

Chased up with AIS
