### ISSUE TITLE
Simplify metro D coordination

### ISSUE THREAD

**Issue by mattkelly4** [vatpac-technology/sops#94]
Discuss with team.  Consider removing clearance for final, airways clearances being relayed from TCU, etc

**Comment by oliverfrye** [comment]
It'd be great if Bankstown TWR, for example, could automatically issue an IFR departure airways as long as they were on the Bankstown 8 at the standard assigned level, for example (much like auto-release for Class C towers, I suppose).

I was on that position last Milk Run and struggled to coordinate in a timely manner with a very stressed-out and overworked Brisbane Center over the top of me - being able to just do the NEXT call would have been helpful IMHO.

**Comment by alexd-332** [comment]
> It'd be great if Bankstown TWR, for example, could automatically issue an IFR departure airways as long as they were on the Bankstown 8 at the standard assigned level, for example (much like auto-release for Class C towers, I suppose).
> 
> I was on that position last Milk Run and struggled to coordinate in a timely manner with a very stressed-out and overworked Brisbane Center over the top of me - being able to just do the NEXT call would have been helpful IMHO.

agreed

**Comment by zachbf** [comment]
I would support simplification and SOPs that allow simply a 'next' call.
